apiVersion: apps/v1
kind: Deployment
metadata:
  name: menu_app_deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: menu-app
  template:
    metadata:
      labels:
        app: menu-app
    spec:
      containers:
      - name: menu_app_container
        image: gsaiadhinathareddy/menu_card:tagname
        ports:
        - containerPort: 80
